server:
  port: 8092

mongo:
  configuration:
    host: localhost
    user: it-provider
    password: "!it-provider"

  db:
    name: provider
    collection:
      ratings: ratings

benzinga:
  token:
    file: "/Users/dimapod/benzinga.token"

kafka:
  active: false

#quartz:
#  job:
#    rating:
#      cron: "0 */1 * * * ?"
#
#    yahoohistoric:
#      cron: "30 */1 * * * ?"
