server:
  port: 8092

mongo:
  configuration:
    host: "localhost"

  db:
    name: "itProvider"
    collection:
      ratings: "ratings"

benzinga:
  token:
    file: "/Users/dimapod/benzinga.token"

quartz:
  job:
    rating:
      cron: "*/2 * * * * ?"
