server:
  port: 8092

mongo:
  configuration:
    host: "localhost"

  db:
    name: "provider"
    collection:
      ratings: "ratings"

benzinga:
  token:
    file: "/Users/dimapod/benzinga.token"

#quartz:
#  job:
#    rating:
#      cron: "0 */1 * * * ?"
#
#    yahoohistoric:
#      cron: "30 */1 * * * ?"
